apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "Codacy"
  annotations:
    backstage.io/techdocs-ref: value
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
