site_name: Node.js template
docs_dir: docs
site_dir: site
nav:
  - Home: index.md
theme:
  name: material
  palette:
    primary: green
    accent: lightgreen
  font:
    text: Roboto
    code: Roboto Mono
plugins:
  - search
  - techdocs-core
